language: node_js
node_js:
- '7'
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
env:
  global:
  - secure: tdRSkZj4Y7y2F8fk78bunU7M4Md7cTiEwIHyCjUgA+SJXiL0FVP+8HxZRpbGkvS2SK3O4HFc6HuI6wkYXP4lyuNtMzdmegPnzhiKqPGav2Jc9REXdfgWGKV/W5Mgbu/GKdEMCg2NWg9RF+KPOveE1NWUM4hoyOvJM/OnI8+aiFH7QwjQMw6GWq4RqnMzO/bLRDV0YuVZucYUIEZyBTfzg6tlJrmyuEg8Qgo1DeGT4ZxC7eklBwaoPB+KC5JOnIeiZoZtPHYPK1y24q76VWWYA2tWPWWDxtJk6k5Ckhbflbin6gHlPO+lS6UfjZzEy8vMEHjKNVxCA8zPEwUcgWMvn1IQIsGrEFB7A45rl+xZ0zkLwdntkPthHIaHv++wRrls78fWqJx3oyilFwYOhr7JGEskJSiDGdtIPpS+2eMZ5tcSpUPYm4IxpKd3WGyaxzw0xpcDWabgWLU4IJTAQs/hgGWh239YS5yfFW9qsK6G5HaZSxKAyWfGVrpqwBIgj6hyLYCg+skluNddf0hiISiTIbOYatAdgqirQ5D/Wp8psfLW1M9cSYZT9dtRs2ca64I4ft7TUEicvZCJl+9UBtG52qwdCxtrvH4bFiViyak7dVwcNaWz7rb6JIl9+mNbmHgDePoR6/elL0oMjvCc6E1G9QTAYv+X6mrJO0eyGd84dc4=
  - secure: Fw2jD5f7KTGZmebPkZxehzuTR8eWQDlsWIEvGfRgtf8qSZcUb0NPUvBUraFW3igV6ddF+w5sgEH9xxMkxFNrBhpvBYPykMDxqEsOeGMK/ZKsdkQheZJ0suDygLQ3BcT86YctJHhYMm55xx69pmpcr8X4KlWoDqmJ/SEcMaJEHBzGmaGITU+z46vKqaIsvS1SWotEMEDapHRPjQSHn8CJv+kWKExwvPGEKUpbBw4FqfKwmop6swy87N7dWqlSONM2QqrLGnISQiT5TyGCb0cHIf9R4WzdZiprxVIOZ1VNWm3+YHWA4MGTod78JU1pvdQExsAbYq9Yo8AOI+ELs+xb8z9PoNB/3j7htdN/HaoUZ5ObSFFrjHJPeO0IyHXFKaBtSYikIYmHVCoITd18jYr7zTdpXUG6qOdXTVS0gMtZYvNe1W+21YuY+97b5KBp+LqJUBFrlYwApDY/RG7MmhBaxDDus5Mo7r7dtDRdoZoz/pDlrMLp4Mf2t5qWRGqKluzA9w2KAtEjnoKhFuQ7iDXNuTOaI/oyIh6lBoJHOO1Eahi3+jCx7R2wOeOwt38h8HS65fdpu4Am4cjpkRgLNy/UJG4BM1BODKopUvi3Lh4oJuAgasvq2TifsJOGUNJHJeTa5A3gZdOt//JK0kgSc/lBfq0K2IaVKr7nsNwWtlbR/YY=
