language: node_js
node_js:
- '7'
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
env:
  global:
  - secure: TOQ/mAdVOQi5DR7q2ho7RJG5ohWp+TmwxY5A8BDVB9wN78T/Zm+Qa7RdzM+vIrQZisCRJHetAU9CipmMyUBZ/za9MRerAOWhz72QqSFCUatpW7c1ThUpJeALtRVMzDkp34VNFgVcUAeqQXttr/Wnr7Sla/0OyUtN6VZOT0mQE19XcCrB/nqyf3IspRXFHAj6LQZI+PYe0HkReqxLdPRSo+QMxU1Ip8zHudu6R8+Azk5ttXd63J1m8w40vWAMwpM1p1dtICXPxToNpcSmIYLdKw0ZO8UZWBxqJwXWs6yCfjz1P5A5Sl/ewDzOhAIbTsaMWtm9L4L6MyKKUzt/bksvHoDGo+6SjHqDZDSsUnLkKf5nnqeBm4ro46fPtg48WlvlQ/oTLflrUKq97TaIMK+Whw9AvF1H6SrZW49j4o4zq31xG8ciAyABollwbkIjbJ14HLCZfinavbbpWrMjEV6XwCZonolynb6FaZMbY6T5dNupXrLz7iv+s4BoR/iBDy8lgG0bbIDpknmePafZd3jhnMRaqoKNNE8rokQ4JpQ7BbzPstedhMTf9xJwUFZR0LOJtUVSBovjcPHU/3U87URnRxISmzQo1CURe4GhRa5JFWc0Cq7vNz8j9EaA2Va7PqMXkcORKc4Wz0O9O8+CsBiqxo/ILdjbx04v+7KOSMAJscc=
  - secure: X77UOMkoxSBYw28dijNhMzN+rMpEsMqAvxPra9YrCw4i88+hNvcEbLrxp+zjvjZeP8Bbhk61GQkh1AKY93Cie+2uz0hNb/VH8vky+NENTQNucoxYYQjbcobddoBv6pbS2KT+LgD26mShEwSOBXnc4Psy01BQzmgsOrlsUJ+fU1Ow80YxZapsOWjBYbXuK5PVDIIw6Y95TIPMrYkmq8ruIipK4lPnzFynIzgTeLcSHK4eS2jvM8B+3zQzKEWo9XWpxWe6EGjKwlJHNzv98RI9ANS9g3oxB4EgUb7k+MOAMZof2GnGccoACtbXAuTHKWKDOI3Vx3kZndi0CyoGRl/qrUkEOWqAhOPIvqQQ0qEQunAr2/QZ+alhOXojaFtoIPjTII+Jqf57eofnQdt94frqRplQ8Yc9u+l+7EyLHihctckmP2erBFr5rVPKhkhAVAbPD5oOBrBME2zIBvkxIiIbMxGsI7wrGm3/h8XNd9oqnl4HgcQASEH29i2peAczeLfcUctPsgQBYl+dK/0uFxN1UYOa0Q/AScliQ3dXOCOTvKNVB0SE04umkZW6V91YP3EFfYnJ3+JtXFZxTGSpXPNlY8B3qJ2csbV2GqrXA1OVn3ReqcKfSb7h9SjyjQHYysLkzue2AL1zcEnmjuyD0kEqdX22Mx2SiBUTjf305Xw7wVs=
